version: '3'

services:
  app:
    image: node:lts
    command: >
      bash -c "cd /app &&
               npm install &&
               npm run dev"
    volumes:
      - .:/app
    ports:
      - 3000:3000
